version: '3.8'

services:
  postgres_db:
    image: postgres:15-alpine
    container_name: postgres_database
   restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app_network

  backend:
    image: naimaomo/trovr-backend:latest
    container_name: trovr-backend-api
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      DB_HOST: postgres_db
    depends_on:
      - postgres_db
    networks:
      - app_network

  frontend:
    image: naimaomo/trovr-frontend:staging
    container_name: trovr_frontend
    restart: always
    ports:
      - "80:80"
    networks:
      - app_network

volumes:
  pgdata:

networks:
  app_network:
    driver: bridge
